########################################################################
#$$$$$$$$\ $$$$$$$$\  $$$$$$\  $$$$$$$\  $$\   $$\  $$$$$$\  $$\   $$\ #
#$$  _____|$$  _____|$$  __$$\ $$  __$$\ $$ |  $$ |$$  __$$\ $$ |  $$ |#
#$$ |      $$ |      $$ /  $$ |$$ |  $$ |$$ |  $$ |$$ /  \__|$$ |  $$ |#
#$$$$$\    $$$$$\    $$$$$$$$ |$$$$$$$  |$$ |  $$ |\$$$$$$\  $$$$$$$$ |#
#$$  __|   $$  __|   $$  __$$ |$$  __$$< $$ |  $$ | \____$$\ $$  __$$ |#
#$$ |      $$ |      $$ |  $$ |$$ |  $$ |$$ |  $$ |$$\   $$ |$$ |  $$ |#
#$$ |      $$ |      $$ |  $$ |$$ |  $$ |\$$$$$$  |\$$$$$$  |$$ |  $$ |#
#\__|      \__|      \__|  \__|\__|  \__| \______/  \______/ \__|  \__|#
########################################################################
#This plugin is made by SkyfightTV for everyone
#It works between spigot version 1.7 and 1.16
#This plugin can't be reloaded

IsSetup: false

#DebugMode sends a message to the console each time an event is called
#/!\ The debugmode can spam the console /!\
DebugMode: false

#Enable or disable color message in the console
ColorConsole: true

Worlds:
  Number: 5
  Increase: 2
  Title: "CTS-"
  Copy: "world"

##############################################
# __  __  ___  ____  _   _ _     _____ ____  #
#|  \/  |/ _ \|  _ \| | | | |   | ____/ ___| #
#| |\/| | | | | | | | | | | |   |  _| \___ \ #
#| |  | | |_| | |_| | |_| | |___| |___ ___) |#
#|_|  |_|\___/|____/ \___/|_____|_____|____/ #
##############################################
#Enable or disable modules

#After update, reload the plugin or restart the server

CTS:
  Kits: true
  Play: true

###########################################################################
#  ____ ___  _   _ _____ ___ ____ _   _ ____      _  _____ ___ ___  _   _ #
# / ___/ _ \| \ | |  ___|_ _/ ___| | | |  _ \    / \|_   _|_ _/ _ \| \ | |#
#| |  | | | |  \| | |_   | | |  _| | | | |_) |  / _ \ | |  | | | | |  \| |#
#| |__| |_| | |\  |  _|  | | |_| | |_| |  _ <  / ___ \| |  | | |_| | |\  |#
# \____\___/|_| \_|_|   |___\____|\___/|_| \_\/_/   \_\_| |___\___/|_| \_|#
###########################################################################
#After update, restart the server

#Setting up the game
Game:
  MaxPlayers: 16
  MinPlayers: 14
  #Time after spawn when the player is invincible in second
  Invincibility: 5
  TeamSizeZone: 5
  EndGameTime: 10
  WaitTime: 30
  #Command execute when a player was kill by an other player
  #Variables:
  #%victim% = player killed by the damager
  #%damager% = player who killed the victim
  KillCommand: "eco give %damager% 150"

GUI:
  Kits:
    Title: "Menu des kits"
    Size: 27
  Teams:
    Title: "Choisi ta team"
    Size: 9
    Items:
      BlueTeam:
        Material: BLUE_BANNER
        Title: "Team bleu"
        Lore: [ ]
        Location: 4
      RedTeam:
        Material: RED_BANNER
        Title: "Team rouge"
        Lore: [ ]
        Location: 6

#Setting up customs items in the lobby
LobbyItems:
  StartItem:
    Material: DIAMOND_AXE
    Title: "Start Game"
    Lore: [ ]
    Location: 4
    Command: "CTS play"
  KitsItem:
    Material: CHEST
    Title: "Kits"
    Lore: []
    Location: 5
    Command: "CTS kits"

#Config the AutoDeleter which allows you to automatically delete some blocks you own
AutoDelete:
  #List of all blocks can be delete
  Blocks:
    - STONE
    - DIRT
  #Time before deleting block in second
  Time: 10